### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by tausi0661** [daidodo/diablo_edit#1]
First I would say it is an excellent tool. Yes, after I installed HeroEditor but could not open the char file I googled this tool and it just works. No installation, no dll files required!

But here I want to report some display issue, although it doesn't block my usage 👍 
version: v3.0 (the release one on github)
my OS: windows 10

![image](https://user-images.githubusercontent.com/11828012/88355575-acbc5180-cd97-11ea-9efc-2bc14d5b96e8.png)

**Comment by daidodo** [comment]
@tausi0661, thanks for your feedback!

Unfortunately, I don't have much time on this project but I'll welcome PRs of any improvements.
