### ISSUE TITLE
view of the app is not correct

### ISSUE THREAD

**Issue by gbbbs22** [daidodo/diablo_edit#11]
Hi,

inventory view show not correct. the tickbox is in the middle of the inventar etc..

https://abload.de/image.php?img=unbenanntiakph.png

**Comment by xGnoSiSx** [comment]
I have the same issue

**Comment by jlu511** [comment]
10*10大箱子和8*10大背包，显示不正常。

**Comment by daidodo** [comment]
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.29.
