### ISSUE TITLE
语言设置未保存

### ISSUE THREAD

**Issue by zerokos** [daidodo/diablo_edit#12]
开发者看得懂中文不？
菜单View-language-选择简体中文
下次打开程序又是默认英文，希望能够解决
不管是文件还是注册表，弄一个保存语言设置的地方就好了

**Comment by daidodo** [comment]
@zerokos，谢谢反馈！

这个建议很好！只是我不是专门的Windows开发，所以暂时不清楚要怎么做。
如果你有兴趣，欢迎提交PR！

基本原则就是保持程序的绿色轻便（单个exe）。

**Comment by zerokos** [comment]
@daidodo 
我也不懂开发，说一下可以不写入文件或注册表的一点想法
能不能加个检测系统语言的代码，系统语言是简中的就调用简中界面，系统语言是繁中的就调用繁中界面，其他情况通通调用英语界面
开发大大幸苦了

**Comment by zerokos** [comment]
@daidodo 
https://blog.csdn.net/kyfvc/article/details/41074729
这里有个例子，可以参考一下

**Comment by daidodo** [comment]
非常感谢您的建议！
已经在新的版本中改进：[v0.10](https://github.com/daidodo/diablo_edit/releases/tag/0.10)

**Comment by zerokos** [comment]
> 非常感谢您的建议！ 已经在新的版本中改进：[v0.10](https://github.com/daidodo/diablo_edit/releases/tag/0.10)

已更新，现在一打开就是中文舒服多了，谢谢开发大大
