### ISSUE TITLE
Build 0.8

### ISSUE THREAD

**Issue by huertgenwald** [daidodo/diablo_edit#14]
With the padding change, i'm an unable to open my savegames. Error message : ( p j) Unrecognized Item Code
[Savegame.zip](https://github.com/daidodo/diablo_edit/files/7663341/Savegame.zip)

**Comment by daidodo** [comment]
@huertgenwald 
 
Thanks for the feedback!

The issue is (possibly) fixed by [v0.9](https://github.com/daidodo/diablo_edit/releases/tag/0.9).

Interestingly, some simple items (e.g. Antidote Potion) don't have the padding 1 bit as I thought in https://github.com/daidodo/diablo_edit/issues/13.

**Comment by huertgenwald** [comment]
v0.9 opens my savegame. 👍
