### ISSUE TITLE
显示错误，DPI200%

### ISSUE THREAD

**Issue by liuquanqing** [daidodo/diablo_edit#16]
![](https://s2.loli.net/2022/02/06/wAyXxkPhYQTJ1nN.png)
![image-20220206213459348](https://s2.loli.net/2022/02/06/5ZyXSHMPupDGFWi.png)

**Comment by Klamist** [comment]
右键exe属性，第二栏兼容性，更改高DPI设置，替代高DPI缩放，改为“系统(增强)”，就能正常了。
虽然依然有些地方不对。
![1](https://user-images.githubusercontent.com/33776012/165875011-fc835ba6-25ac-46f4-ac65-e9b1f24da66b.png)
![2](https://user-images.githubusercontent.com/33776012/165875012-6c41f8f1-23a4-4b1b-9314-1099b5ccb2e3.png)
![3](https://user-images.githubusercontent.com/33776012/165875013-9848183b-d3ac-4cba-a9c7-95af604f7325.png)
![4](https://user-images.githubusercontent.com/33776012/165875002-feab2a3a-26ce-426a-b84f-0e66c4eb1f38.png)

**Comment by daidodo** [comment]
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.29.
