### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Akaaodd** [daidodo/diablo_edit#18]
I downloaded editor, but did get how touse. I have old version and it's just 1 .exe file, but there is no any .exe files. How to launch?

**Comment by daidodo** [comment]
Hi, I'm not sure what exactly your question is.

You should be able to find an executable in [the release](https://github.com/daidodo/diablo_edit/releases/tag/0.14). It's an editor for d2s file, which is the local Diablo2 character save file.

The position of d2s files depends on your OS. But in my Windows 10 they're under *Saved games\Diablo 2 Resurrected\…*.

Please tell me if you have more questions.

Thanks!

**Comment by Akaaodd** [comment]
Yeah, can't find this bгtton.

**Comment by daidodo** [comment]
Which button?

**Comment by Akaaodd** [comment]
release

**Comment by daidodo** [comment]
Why do you need a release button? What do you try to do?

**Comment by Akaaodd** [comment]
Nothing already, thanks for the link.

**Comment by daidodo** [comment]
Is there anything else I can help?

**Comment by Akaaodd** [comment]
Nope.
