### ISSUE TITLE
中文名字乱码，并且无法保存

### ISSUE THREAD

**Issue by hygz2022** [daidodo/diablo_edit#19]

**Comment by cooper436** [comment]
相同问题，我是用这工具改成英文名，再把存档的名称也改成英文名，就不报错了

**Comment by hygz2022** [comment]
谢谢

**Comment by hygz2022** [comment]
> 相同问题，我是用这工具改成英文名，再把存档的名称也改成英文名，就不报错了

谢谢

**Comment by daidodo** [comment]
请问你们的角色名字是中文吗？
Diablo的版本是什么？
谢谢！

**Comment by daidodo** [comment]
@hygz2022 @cooper436 
问题已在[v0.15](https://github.com/daidodo/diablo_edit/releases/tag/0.15)中解决。
谢谢反馈！

**Comment by cooper436** [comment]
谢谢  辛苦
