### ISSUE TITLE
Can not work with classic character.

### ISSUE THREAD

**Issue by xclid** [daidodo/diablo_edit#2]
First, thank you for ur nice work sir.
But like topic says, won't work with classic character.
pls lmk if you fixd it, ty anyway.

**Comment by daidodo** [comment]
Hi @icecatbing, thanks for the feedback!

Could you share the d2s file that can't be read?

**Comment by xclid** [comment]
[https://github.com/xclid/temp/raw/main/cbus.d2s](d2s file)

**Comment by daidodo** [comment]
@xclid - Thanks for the d2s file!
I've fixed the bug and published a new release v0.2.
Please check it out!

**Comment by xclid** [comment]
Tested.
Everything works fine, thanks for your work.
