### ISSUE TITLE
物品的说明不支持翻译吗？

### ISSUE THREAD

**Issue by fangshun2004** [daidodo/diablo_edit#20]
我在language.txt里面 1443行下面的属性名称 按照 	
`  %+d Strength	%+d 力量		%+d 力量`
这样英文 ---简体中文---繁体中文这样的格式 编译之后 物品的说明里面依旧只有英文的说明

**Comment by daidodo** [comment]
@fangshun2004 
谢谢反馈！

我添加了如何翻译的文档：[CONTRIBUTING.md](https://github.com/daidodo/diablo_edit/blob/master/CONTRIBUTING.md)，希望会有帮助！

**Comment by daidodo** [comment]
所有翻译已经合并且修正：
https://github.com/daidodo/diablo_edit/releases/tag/0.16

谢谢贡献！
