### ISSUE TITLE
Error - item data format error

### ISSUE THREAD

**Issue by Nallatheryth** [daidodo/diablo_edit#25]
Good day, 
I just downloaded the editor and immediately stumbled upon a problem - "Error - item data format error" - see screenshot
playing D2 Resurrected, retail and latest version - 1.2.69807

Please help? :) 
![image](https://user-images.githubusercontent.com/57213261/175550360-ba274d4a-5891-4212-a49a-d3509a4a3d1d.png)

**Comment by daidodo** [comment]
Thanks for the feedback!
Could you share the character file (.d2s)?

**Comment by Nallatheryth** [comment]
[Nallathemiriya.zip](https://github.com/daidodo/diablo_edit/files/9040557/Nallathemiriya.zip)
here is one of the .d2s files. The one in particular caused the issue above.

**Comment by daidodo** [comment]
I was able to edit the character.

Please make sure  you have the latest version: https://github.com/daidodo/diablo_edit/releases/tag/0.16

![image](https://user-images.githubusercontent.com/8170176/177995553-f8cbd12d-e4c3-4a1f-bbbf-9eca61a1616c.png)

**Comment by Nallatheryth** [comment]
Indeed! I don’t know what I was doing wrong before 😊 it works now perfectly.
Thank you very much for your help daidodo 😊



Best Regards
Yordan Ivanov
