### ISSUE TITLE
Just an advice

### ISSUE THREAD

**Issue by LordTreufeldt** [daidodo/diablo_edit#32]
Hi, just to advise you that the character properties Stamina, Life and Mana are all floating point numbers, not integers! Ok.

According to the char level these stats might become floating points.

Could you fix it?

Thank you.

**Comment by daidodo** [comment]
@LordTreufeldt 

Thanks for the feedback!
Could you share some links to support this?

**Comment by LordTreufeldt** [comment]
Hi.

You could check stats for all chars in this link: https://diablo-archive.fandom.com/wiki/

For example. Assassin has floating point stats for life, mana and stamina per level; and per spent points on vitality/energy.

Thank you.

**Comment by daidodo** [comment]
The problem is those values are rounded and stored as integers in the file, even when they might be calculated in floats. So there is nothing I can do here.
