### ISSUE TITLE
Cannot open offline save

### ISSUE THREAD

**Issue by LazyCat-DS** [daidodo/diablo_edit#33]
[2022.09.19.zip](https://github.com/daidodo/diablo_edit/files/9599945/2022.09.19.zip)
I'm using mod https://www.nexusmods.com/diablo2resurrected/mods/2 but several previous saves with this mod was edited successfully (well, increased inventory and stash was not displayed correctly because of some overlaps, but this was not big deal).

**Comment by LordTreufeldt** [comment]
I found another error when trying to open a char with a Scroll of Resistances on inventory (Quest reward from Mala, ACT V). The editor splashes an error on opening the char.

**Comment by daidodo** [comment]
Thanks for the feedback!
@LazyCat-DS: it's known that increased inventory and stash will cause problem because the index will be out of bound.
@LordTreufeldt: Could you share the d2s file?

**Comment by LazyCat-DS** [comment]
Same save - attached to my original post. As I remember some items in inventory and stash are outside original grid. Or new one, attached. Both can be opened and edited (first after using Scroll), so issue is only with UI - Items outside original grid cannot be selected or pasted, and if there is something there - it overlaps with other controls.
[LzCat.zip](https://github.com/daidodo/diablo_edit/files/9643189/LzCat.zip)

**Comment by daidodo** [comment]
This should be solved by https://github.com/daidodo/diablo_edit/releases/tag/0.20.

Please tell me if you have more questions.
Thanks!
