### ISSUE TITLE
Savegame changes in v2.5

### ISSUE THREAD

**Issue by huertgenwald** [daidodo/diablo_edit#34]
See 

https://news.blizzard.com/en-us/diablo2/23827590/diablo-ii-resurrected-patch-2-5-now-live

at bottom of post

HtH

**Comment by Drendar99** [comment]
Had no choice but to download the update if I wanted to play, so I went and created a test character. It does look like the current version of the editor can't save now. (Screenshot of error and test save included if they help.)
[Testbarb.zip](https://github.com/daidodo/diablo_edit/files/9629568/Testbarb.zip)
[Patch 2.5 save error.jpg.zip](https://github.com/daidodo/diablo_edit/files/9629570/Patch.2.5.save.error.jpg.zip)

**Comment by daidodo** [comment]
Thanks for the feedback!

I think I've found the issue and will work on solutions soon.

**Comment by daidodo** [comment]
This should be solved by https://github.com/daidodo/diablo_edit/releases/tag/0.20.

Please tell me if you have more questions.
Thanks!

**Comment by Drendar99** [comment]
Thank you for always updating this!

Something might not be exactly right yet. I was able to open a character (Drendar) and make other edits and save without trouble, but when I tried to import a pre-2.5 item that adds resistances, the editor would just close.

So I went to that test character (Swordtest) and tried creating and exporting a resistance amulet (Crimson amulet), which worked just fine. Then I opened Drendar and imported it just fine. But after that, I couldn't open Drendar or Swordtest again. (I get an "Unrecognized Item Code" error.) And if I try to play the characters, it'll say "Failed to join game."

I created a third test character (Testman) and imported the item, leading to the same results.

I'll attach those files and the amulet file. (Maybe I just did something wrong when creating the amulet? It'd be the first time I ever tried creating a resistance-adding item with the editor.)
[Drendar.zip](https://github.com/daidodo/diablo_edit/files/9687047/Drendar.zip)
[Swordtest.zip](https://github.com/daidodo/diablo_edit/files/9687048/Swordtest.zip)
[Testman.zip](https://github.com/daidodo/diablo_edit/files/9687049/Testman.zip)
[Crimson Amulet.zip](https://github.com/daidodo/diablo_edit/files/9687050/Crimson.Amulet.zip)

**Comment by huertgenwald** [comment]
Thanks 🥇

**Comment by daidodo** [comment]
Thanks for the sharing!

Please try https://github.com/daidodo/diablo_edit/releases/tag/0.21 and tell me if you still have problems.

**Comment by Drendar99** [comment]
Looks like everything's working!

I remember you saying a while back that you don't play D2R much anymore, so again, thank you for updating this every time Blizzard changes the save files!
