### ISSUE TITLE
SUNDERED CHARMS item d2i file

### ISSUE THREAD

**Issue by N0FreeLunch** [daidodo/diablo_edit#35]
I made small charms with 'Immunity if Sundered' option of the SUNDERED CHARM
It will help you to add pierce_type_immunity item option.
[d2i file link](https://github.com/N0FreeLunch/diablo/tree/main/immunity_charm)

**Comment by daidodo** [comment]
Thanks, @N0FreeLunch!

I'll update to editor soon!

**Comment by daidodo** [comment]
This should be solved by https://github.com/daidodo/diablo_edit/releases/tag/0.20.

Please tell me if you have more questions.
Thanks!
