### ISSUE TITLE
One rather trivial request

### ISSUE THREAD

**Issue by huertgenwald** [daidodo/diablo_edit#36]
Under Help/About the editor shows program version 3.0.

It would be nice, if it showed the version number used in 

https://github.com/daidodo/diablo_edit/releases

so either currently 0.19 or 3.19

So i could more easily see, if i use an outdated version.

TiA

**Comment by daidodo** [comment]
This should be solved by https://github.com/daidodo/diablo_edit/releases/tag/0.20.

Please tell me if you have more questions.
Thanks!

**Comment by huertgenwald** [comment]
Thanks 👍
