### ISSUE TITLE
2.5 無法開啟使用者存檔

### ISSUE THREAD

**Issue by michlin212** [daidodo/diablo_edit#37]
2.5 無法開啟使用者存檔
能否新增碎滅咒符存檔物件

**Comment by daidodo** [comment]
@michlin212 
谢谢反馈！

能否分享一个拥有碎滅咒符的存档文件？

**Comment by daidodo** [comment]
Please try https://github.com/daidodo/diablo_edit/releases/tag/0.21 and tell me if you still have problems.

**Comment by daidodo** [comment]
@fangshun2004 

我用最新的v0.21可以打开Diablo.d2s。

**Comment by michlin212** [comment]
可以了謝謝  另外能請問哪邊能拿到最新的物品存檔  主要是想要體驗碎滅咒符

**Comment by daidodo** [comment]
@michlin212 
https://github.com/daidodo/diablo_edit/issues/39
