### ISSUE TITLE
v0.20，Suspended charms, error in editing variables

### ISSUE THREAD

**Issue by kof758** [daidodo/diablo_edit#39]
Another question, how to change the three appearances of charms?

**Comment by kof758** [comment]
https://bbs.d.163.com/forum.php?mod=viewthread&tid=174690444
2.5破免存档下载

**Comment by kof758** [comment]
2.5 charms d2s download

https://bbs.d.163.com/forum.php?mod=attachment&aid=NDAzNTk2NXw1MTRmY2ExMnwxNjY0NjQwNTgyfDkyNTE4NXwxNzQ2OTA0NDQ%3D

https://bbs.d.163.com/forum.php?mod=viewthread&tid=174690444

**Comment by daidodo** [comment]
Thanks for the feedback!

You can't chagne appearance of items because it's fixed in the editor for simplicity.
