### ISSUE TITLE
This char has a "Maul" 2x3 in size that cannot be acessed in editor

### ISSUE THREAD

**Issue by LordTreufeldt** [daidodo/diablo_edit#41]
Hi.

I noticed that the editor cannot access mauls in inventory or stash that have 2x3 in size. Only 2x4 mauls can be acessed!

This barbarian char has a maul in the inventory that cannot be acessed by editor!
[Krull.zip](https://github.com/daidodo/diablo_edit/files/9728206/Krull.zip)

**Comment by daidodo** [comment]
Thanks for the feedback!

Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.24.
