### ISSUE TITLE
act5 barbarian Frenzy mercenary cannot be supported

### ISSUE THREAD

**Issue by SmileKermit** [daidodo/diablo_edit#42]
Thanks for your support.

1. Act5 barbarian Frenzy mercenary cannot be supported

There's blank for that Type

2. [188] Skill Code 0 and 1 overlapped. There is no distinction between the two. 

I'm always rooting for you

**Comment by daidodo** [comment]
Thanks for the feedback!

Could you share the d2s file for me to understand the issue?

**Comment by SmileKermit** [comment]
Here's my .d2s files. 
 
Thanks for your message!
-----Original Message-----

**Comment by daidodo** [comment]
@SmileKermit 
Sorry, I don't see the file.

**Comment by daidodo** [comment]
Duplicate to https://github.com/daidodo/diablo_edit/issues/45.

**Comment by daidodo** [comment]
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.26.
