### ISSUE TITLE
To Add FireStorm (Diablo Wall Spell) as Skill

### ISSUE THREAD

**Issue by LordTreufeldt** [daidodo/diablo_edit#43]
Hi.

Can you add the FireStorm Skill (Diablo Firewall Spell) in the 'Other' item properties for Skills with the '%Chance to Cast Level XX when ...'?

The game accepts this skill as you can see bellow:

![Screenshot002](https://user-images.githubusercontent.com/99281698/195335999-211bfdb4-a0c5-47d4-8a9c-a9a0a8c89215.png)

The Skill Code is 197

Thank you.

**Comment by daidodo** [comment]
Thanks for the feedback!

Could you share the d2s file with this small charm?

**Comment by LordTreufeldt** [comment]
Here goes: 
[Rordak.zip](https://github.com/daidodo/diablo_edit/files/9779661/Rordak.zip)

**Comment by daidodo** [comment]
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.25.

Thanks!
