### ISSUE TITLE
請問 editor 0.26 版本無法更改技能板的屬性, 例如法師的技能板永遠都是火板

### ISSUE THREAD

**Issue by michlin212** [daidodo/diablo_edit#47]
請問 editor 0.26 版本無法更改技能板的屬性, 例如法師的技能板永遠都是火板

**Comment by daidodo** [comment]
谢谢反馈！
能否分享一下你的d2s存档以便我重现问题？

**Comment by michlin212** [comment]
[Diablo II Resurrected.zip](https://github.com/daidodo/diablo_edit/files/9953428/Diablo.II.Resurrected.zip)
人物裡面有個火板, 要改成電板
