### ISSUE TITLE
打开不朽之王的碎魂者存档错误

### ISSUE THREAD

**Issue by feirnova** [daidodo/diablo_edit#48]
[testz.zip](https://github.com/daidodo/diablo_edit/files/9969898/testz.zip)
有不朽之王碎魂者的存档读取错误，直接退出，麻烦看下什么问题，上面压缩包是存档
下图为具体碎魂者的属性截图
![企业微信截图_20221104155423](https://user-images.githubusercontent.com/15042986/200806718-5d4b1d26-a86e-41c8-99e7-9015bb46e7dc.png)

**Comment by daidodo** [comment]
谢谢反馈！
你分享的存档文件无法加载进游戏，可能是存档本身的问题。
