### ISSUE TITLE
view of the app is not correct

### ISSUE THREAD

**Issue by aacaai** [daidodo/diablo_edit#49]
![image](https://user-images.githubusercontent.com/117637228/201044993-8df0aae8-df7a-41e6-97c5-133953dc68f9.png)

画面显示不正确  可以更新吗

**Comment by daidodo** [comment]
Duplicate of https://github.com/daidodo/diablo_edit/issues/11

**Comment by daidodo** [comment]
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.29.
