### ISSUE TITLE
Corpse data format error

### ISSUE THREAD

**Issue by Jordi1990** [daidodo/diablo_edit#5]
I'm seeing 'Corpse data format error' when loading attached save game(D2R). I was able to edit it before, suddenly I am getting this error.

Tested on latest 0.4.

[Neclioplatra.zip](https://github.com/daidodo/diablo_edit/files/7272011/Neclioplatra.zip)

**Comment by daidodo** [comment]
@Jordi1990 - Thanks for the feedback!

I tried the character in D2R and couldn't load it. (D2R crashes)
After investigation, the problem is the equipped amulet has an unknown property (code 500).
I don't know what I can do here. Sorry!
