### ISSUE TITLE
Generate Data / TXT file modding support

### ISSUE THREAD

**Issue by Jascen** [daidodo/diablo_edit#50]
Thank you for this project. It provided me with a GUI to fix some errors with my characters that I managed to break.

I would like to fork this for the Project Diablo 2 mod and I was wondering how you put together your files for "itemdata.txt" in the "Generate Data" project.

For what it's worth, [separate app](https://github.com/Jascen/d2-stash-organizer/tree/main/game-data/txt) that I have forked , I am using the text files that are [extracted from the MPQ](https://github.com/BetweenWalls/PD2-Singleplayer#modification), which is a common way to modify the game.

**Comment by daidodo** [comment]
Thanks for reaching out!

I used text mods to generate "itemdata.txt", too. But it was long ago (before Resurrected). And as you may see, I combined several files together and kept/translated only useful attributes for the tool.

Feel free to tell me if you have more questions!

**Comment by Jascen** [comment]
Thanks for the response. Looks like I'll need to do something manually to cherry-pick and merge into a single file if I'm looking to use this app, then.
