### ISSUE TITLE
Can't import an item just exported

### ISSUE THREAD

**Issue by dingelish** [daidodo/diablo_edit#51]
Hi there, I love this tool very much. But I can't import any item exported by this tool in the latest version (0.27). Items exported by previous version of this tool can be imported smoothly in 0.27. Please advise. Thanks!

**Comment by dingelish** [comment]
d2s here for you to reproduce. can't import the exported the fort war scepter

[PAL.zip](https://github.com/daidodo/diablo_edit/files/10054655/PAL.zip)
[Fortitude Superior War Scepter.zip](https://github.com/daidodo/diablo_edit/files/10054663/Fortitude.Superior.War.Scepter.zip)

**Comment by daidodo** [comment]
Thanks for the feedback!

Please try https://github.com/daidodo/diablo_edit/releases/tag/0.28.

**Comment by dingelish** [comment]
Amazing! Thank you for the quick fix!
