### ISSUE TITLE
max durability modify error

### ISSUE THREAD

**Issue by khsmath** [daidodo/diablo_edit#55]
Thank you for this project. I always use this gratefully.

Issue: I can't save correctly superior items with max durability option.

![dur 1](https://user-images.githubusercontent.com/121308306/209370586-9d0bcb9e-22f9-4525-817b-c5564fe8bdbf.png)
![dur 2](https://user-images.githubusercontent.com/121308306/209370660-fd5e5806-4a11-4860-b44f-d214bdbbece2.png)

![dur 3](https://user-images.githubusercontent.com/121308306/209370683-18b1264a-733a-4d63-981b-92e55be292e5.png)
ex) A superior diadem with max durability option has 23/23 dur, but in this edit, only modified 20/23 dur.

**Comment by daidodo** [comment]
Thanks for the feedback!

From the screenshots, the max dur is 20 while you tried to set current dur 23.

If you believe it's a bug of the tool, please share the character save file (.d2s) or item file (.d2i).

**Comment by daidodo** [comment]
Please try https://github.com/daidodo/diablo_edit/releases/tag/0.30 and tell me if you still have issues.
Thanks!
