### ISSUE TITLE
Just FYI: PTR for Patch 2.6

### ISSUE THREAD

**Issue by huertgenwald** [daidodo/diablo_edit#57]
https://news.blizzard.com/en-us/diablo2/23893117

**Comment by LordTreufeldt** [comment]
New item atributtes coming to add to 2.6 save format.

* +XX% chance for finishing moves to not consume charges. (Mosaic Runeword)
* Mark of the Wolf grants +20% Bonus to Attack Rating, Increase Maximum Life 40%. Lasts 180s. (Metamorphosis Runeword)
* Mark of the Bear grants +25% Attack Speed, +25% Chance of Crushing Blow, Physical Damage Received Reduced by 20%. Lasts 180s. (Metamorphosis Runeword)
* Burst of Speed can now be used by any class in % chance on striking, on attack, when struck, skill charges and go on. (Hustle Runeword)

**Comment by LordTreufeldt** [comment]
I haven't played yet the PTR 2.6 because I'm in my holidays. Sorry, I don't have any chars at this moment.

**Comment by dingelish** [comment]
@daidodo Please checkout the following links
2.6 符文組測試角色單機檔下載
砲轟馬：[http://shorturl.at/gxDEZ](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1F2U1otTHJKR0paQ3pDVXVDQ0JrM2tIRUhzUXxBQ3Jtc0tsdTZZcTZhRE12Tnd3QnI1S1BBaGZBZ0Zka2tPX091cFpYeVV0MlEwd1ZxR1ZwckZRa3pvMXZkZFZFWS1BeFRmYjVleWI5SVgwT25KLXdUQllyS3U2TWljUG44R3BfZVRJRlpsRzBTd1ktUVFxbjRBOA&q=http%3A%2F%2Fshorturl.at%2FgxDEZ&v=taL2ljnL2mQ)
鳳凰刺：[http://shorturl.at/cdftD](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbU5MWk5kX3EwdkNicHNXRnlUTlRtZ2tId1RBUXxBQ3Jtc0ttbE1YR3hkdmdjNWZKVmpnaFdBMGtEZW9xb253Vi1ISjNRNHZDYkx1MENZVURpb0d0NUY3WHViMlI4eDRKUVJIZzZYMFFwcERDUl9UNW9mMWJidDJyc0V1S1pSY1l0SUNMd2NaYjI1NEhXRU5ZRHNmQQ&q=http%3A%2F%2Fshorturl.at%2FcdftD&v=taL2ljnL2mQ)
焰爪熊：[http://shorturl.at/eKVZ2](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1BRT3RhcmdyY0NwVzB3emFXVDFFUl9KN0hRUXxBQ3Jtc0ttSzVaQWNDUGhKaVMweWVqRHFiUGhtYnNyUVhnSkdNLXdSdnkyUzMxWmxlb1Q2ckVOYUtob3ktSVRmQ240YU1KYmZQRFdrMHNvV1BMSHpuMFJhZlA0RkUzUGpVNEVOMUtsUHFnUVhfbThvZ2pXM2FiOA&q=http%3A%2F%2Fshorturl.at%2FeKVZ2&v=taL2ljnL2mQ)

**Comment by daidodo** [comment]
Thanks a lot for the files, @dingelish !

For completion, do you have all new runewords? I can't release with partial support.

**Comment by dingelish** [comment]
Just found this: [https://tinyurl.com/Ggmsitempack](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbnZmREhBWklNTktGOTdxNkRLSzBFamRNa05DQXxBQ3Jtc0tuRFdfSFhUU1JBREh4SENNemd0emNoeE9lZ2M4MFo5Nms0N2RfOGxCZmJxdlFCcHFfUHl0ODRzaFUzaFEtczlvLUpObUtVWmZ0QXlqZ1NRTnc4Qms2SUpOTnFlMTVHNjZBU2RrZVFhcnZqMTVaUzNLRQ&q=https%3A%2F%2Ftinyurl.com%2FGgmsitempack&stzid=UgyZtAEVCLyGzkyNCHx4AaABAg)

RWs are:
- `GGM's Item Pack\Mock Runewords For D2LoD Users\BulwarkRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\CureRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\GroundRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\HearthRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\HustleRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\TemperRW`
- `GGM's Item Pack\Mock Runewords For D2LoD Users\MetamorphosisRW`

Can't find Mosaic in this pack but I guess it's included in 鳳凰刺：[http://shorturl.at/cdftD](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbU5MWk5kX3EwdkNicHNXRnlUTlRtZ2tId1RBUXxBQ3Jtc0ttbE1YR3hkdmdjNWZKVmpnaFdBMGtEZW9xb253Vi1ISjNRNHZDYkx1MENZVURpb0d0NUY3WHViMlI4eDRKUVJIZzZYMFFwcERDUl9UNW9mMWJidDJyc0V1S1pSY1l0SUNMd2NaYjI1NEhXRU5ZRHNmQQ&q=http%3A%2F%2Fshorturl.at%2FcdftD&v=taL2ljnL2mQ)

**Comment by daidodo** [comment]
@dingelish 
Unfortunately, they are not real RWs:

![image](https://user-images.githubusercontent.com/8170176/216575682-35f1b6c1-8140-4548-a799-c993f02e212a.png)

**Comment by daidodo** [comment]
Please try https://github.com/daidodo/diablo_edit/releases/tag/0.31 and tell me if there is any problem.

Thanks!
