### ISSUE TITLE
Wrong Pictures and Stats for Druid Pelts

### ISSUE THREAD

**Issue by LordTreufeldt** [daidodo/diablo_edit#59]
Hi, just a bug that I found today when editing a Druid Char with Pelts.

I attached 2 item files that can be imported via editor to any char.
[Dream Spirit.zip](https://github.com/daidodo/diablo_edit/files/10759833/Dream.Spirit.zip)
[Sky Spirit.zip](https://github.com/daidodo/diablo_edit/files/10759830/Sky.Spirit.zip)

The **Dream Spirit Pelt** is with the wrong picture appearing in the editor.
The **Dream Spirit Pelt** is a Wolf Head and has the following stats in game:
+ 7 Druid Skills
+ 7 Lycanthropy
+ 7 Shape Shifiting Skills

But in the editor **The Dream Spirit** is showing a Falcon Head (the correct is a Wolf Head) and has inverted Tab Skills with Single Skills Levels descriptions:
+ 7 Druid Skills (83)
+ 7 Shape Shifting Skills (107)
+ 7 Lycanthropy (188)

---------------------------------------------------------------

The **Sky Spirit Pelt** also is showing the wrong picture in the editor.
The **Sky Spirit Pelt** in game is a Falcon Head, but in the editor is showing a Wolf Head.

**Comment by daidodo** [comment]
The pics are fixed in [v0.33](https://github.com/daidodo/diablo_edit/releases/tag/0.33).
