### ISSUE TITLE
Unable to save edited character after completing first playthrough on Normal difficulty.

### ISSUE THREAD

**Issue by angelvet** [daidodo/diablo_edit#6]
For example when I import an item or just move an item from a stash into the backpack and save the character, nothing happens.
After reloading my character file, everything is in its original state, no changes are saved.

When I tried "Save As" option I've got an error "Encountered an improper argument."

Thanks!

[Nigga.zip](https://github.com/daidodo/diablo_edit/files/7278468/Nigga.zip)

**Comment by daidodo** [comment]
Hi, thanks for the info!

The issue should be fixed by https://github.com/daidodo/diablo_edit/releases/tag/0.5.
