### ISSUE TITLE
[Suggest] change skills name

### ISSUE THREAD

**Issue by N0FreeLunch** [daidodo/diablo_edit#63]
The editor is working great for me. Thanks for the ongoing support!

I couldn't find skill solar creeper.
In this editor, The name of the solar creeper is defined vine, and the name of the carrion vine is defined cycle of life.
[cycle of life](https://github.com/daidodo/diablo_edit/blob/89adae5067a54bbde7eaa23c4ca80385b488a866/Generate%20Data/language.txt#L706)
[vine](https://github.com/daidodo/diablo_edit/blob/89adae5067a54bbde7eaa23c4ca80385b488a866/Generate%20Data/language.txt#L709)

I suggest to change skill name.
vine => solar_creeper 
cycle of life => carrion_vine 

[reference](https://diablo2-doc.readthedocs.io/01-%E4%BF%AE%E6%94%B9%E5%B7%A5%E5%85%B7%E8%BD%AF%E4%BB%B6/01-UdieTool/02-%E6%8A%80%E8%83%BD%E4%BB%A3%E7%A0%81/index.html#id3)

**Comment by daidodo** [comment]
Thanks for the feedback!

Could you point me to the links of the official names?

If it's changed in D2R, I'm happy to accept a PR.

**Comment by N0FreeLunch** [comment]
Thank you for your reply.

The skill names in Diablo resurrected data's skills.txt file are still the same. However, these are not the names that are displayed in the game. It seems that it is necessary to use the names that are displayed in the game.

https://news.blizzard.com/en-us/diablo2/23765907/diablo-ii-resurrected-patch-2-4-balance-ptr-has-ended
The skill names "Carrion Vine" and "Solar Creeper" are used in the above link.

As there is no official document listing these skill names, their usage can be verified through the wiki or game content.
https://diablo.fandom.com/wiki/Carrion_Vine
https://diablo.fandom.com/wiki/Solar_Creeper

**Comment by daidodo** [comment]
Could you share screenshots of the skill names (better in English, SimplifiedChinese and Traditional Chinese) in the game?

I can't verify it myself. Thanks!

**Comment by N0FreeLunch** [comment]
The names of each skill can be found in the [skills.json](https://github.com/daidodo/diablo_edit/files/15097231/skills.json) file.

```json
{
    "id": 22042,
    "Key": "Skillname223",
    "enUS": "Poison Creeper",
    "zhTW": "劇毒藤蔓",
    "deDE": "Giftkriecher",
    "esES": "Enredadera venenosa",
    "frFR": "Lierre empoisonné",
    "itIT": "Rampicante Velenoso",
    "koKR": "맹독 덩굴",
    "plPL": "Trujący Pełzacz",
    "esMX": "Liana venenosa",
    "jaJP": "有毒なる蔦",
    "ptBR": "Trepadeira Venenosa",
    "ruRU": "Ядовитая лоза",
    "zhCN": "毒花藤"
  },
```

```json
{
    "id": 22078,
    "Key": "Skillname232",
    "enUS": "Carrion Vine",
    "zhTW": "食屍藤蔓",
    "deDE": "Aasranke",
    "esES": "Liana carroñera",
    "frFR": "Liane charognarde",
    "itIT": "Vite Carogna",
    "koKR": "청소부 덩굴",
    "plPL": "Nekrorośl",
    "esMX": "Liana carroñera",
    "jaJP": "血に飢えた蔦",
    "ptBR": "Vinha Carniceira",
    "ruRU": "Трупная лоза",
    "zhCN": "食尸藤"
  },
```

```json
{
    "id": 22118,
    "Key": "Skillname242",
    "enUS": "Solar Creeper",
    "zhTW": "太陽藤蔓",
    "deDE": "Sonnenkriecher",
    "esES": "Enredadera solar",
    "frFR": "Lierre solaire",
    "itIT": "Rampicante Solare",
    "koKR": "태양의 덩굴",
    "plPL": "Słoneczny Pełzacz",
    "esMX": "Liana solar",
    "jaJP": "魂喰らいの蔦",
    "ptBR": "Trepadeira Solar",
    "ruRU": "Солнечная лоза",
    "zhCN": "太阳藤"
  },
```

![carrion vine](https://github.com/daidodo/diablo_edit/assets/47421082/1722b3e4-3e4c-4d17-b3b9-57257167a61e)
![poison creeper](https://github.com/daidodo/diablo_edit/assets/47421082/5d4cc128-cb69-472f-afcb-043a05ddb7d8)
![solar creeper](https://github.com/daidodo/diablo_edit/assets/47421082/984ac19d-49a7-49b1-92a6-c467b195ec9c)
![tw carrion vine](https://github.com/daidodo/diablo_edit/assets/47421082/3eb56d4d-d133-4dd4-982a-9ca58215fe5e)
![tw poison creeper](https://github.com/daidodo/diablo_edit/assets/47421082/634067d1-e969-4bd9-9e49-b8587fa2c8ca)
![tw solar creeper](https://github.com/daidodo/diablo_edit/assets/47421082/2e60eba5-5ce0-4d74-baf2-99f925ac0021)

**Comment by N0FreeLunch** [comment]
Unable to verify as the language pack is not supported for Chinese (CN). 
Because of the language pack for Chinese (CN) is not available.

**Comment by daidodo** [comment]
Thanks for the screenshots!

I may not work on it soon.
If you'd like to make the changes, the file should be language.txt.

**Comment by N0FreeLunch** [comment]
ok, i'll try it.

**Comment by daidodo** [comment]
Released new exe in https://github.com/daidodo/diablo_edit/releases/tag/0.32.
