### ISSUE TITLE
Hope Diablo Edit2 can add substrate modification function

### ISSUE THREAD

**Issue by 17OROCHI** [daidodo/diablo_edit#66]
Necklaces, rings, and jewelry can be directly changed in style, and there are errors in the texture of the Druid special head

**Comment by 17OROCHI** [comment]
武器底材可以直接改其它武器，投掷类直接改投掷类的，项链戒指珠宝可以直接换另一样式，德鲁伊的专用头盔最后那两个贴图错了，应该交换回来，触发技能的列表里应该把所有不能触发的技能去除，暗金装备名字最好可以中文化，另外，套装直接添加绿色词缀时不知道出于什么原因会导致保存时编辑器出错

**Comment by daidodo** [comment]
Sorry for the late response!

> 武器底材可以直接改其它武器，投掷类直接改投掷类的

右键单击物品 / New From / 选择物品类型

> 暗金装备名字最好可以中文化

所有语言和文本在 *Generate Data/language.txt* 里，可参考https://github.com/daidodo/diablo_edit/blob/master/CONTRIBUTING.md#language-support 提交PR。

其他问题需要更详细的描述或示例。谢谢！

**Comment by 17OROCHI** [comment]
装备New From有个问题是，这操作会洗掉套装的绿色词缀，一件装备如果我直接添加绿色词缀，它会在保存时出错，这样就导致想修改套装时十分困难，想更改底材就要另外用到udietoo

**Comment by daidodo** [comment]
单个套装的属性可以直接修改或添加。

听你的描述，似乎想创造新的绿装，或者改变已有绿装的底材，例如头盔改成铠甲。这个操作目前还不支持，因为需要修改绿装名字索引(https://github.com/daidodo/diablo_edit/blob/master/Generate%20Data/language.txt#L4553)，可能涉及mod修改（多个套装的隐藏属性）。

**Comment by 17OROCHI** [comment]
对，使用udietoo可以直接更改底材，前提是只能大致同类相改，否则会字符串出错，只是Ut太老旧了，大部分功能没Edit2方便快捷，一目了然

**Comment by 17OROCHI** [comment]
举例说亚马逊终极套装盔甲，只有3件套的位置有绿色词缀，我的做法就是在udietoo里把不朽之王鞋子改成盔甲，并且名字也改过来，2件套4件套5件套才能有绿词缀，如果直接在Edit2里添加，就会出错

**Comment by daidodo** [comment]
如果你是想要“+30% 快速再度攻击 (3 套装物品)”属性，可以：
1. 再多穿一件马维娜的套装物品，或者
2. 直接把“+30% 快速再度攻击”加到马维娜的铠甲里。

我是觉得，既然已经修改了，加一条属性比改套装底材容易多了。

**Comment by 17OROCHI** [comment]
关键是在修改中要考究装备外形和名字，还想在套装加成里每多装备一件都有新的绿词缀，所以凡是四件套都是艾尔多套装在UT里改了底材再拿到Edit2里改各种属性，五件套武器只有塔拉夏，防具只有不朽鞋，六件套全在不朽套装里

**Comment by 17OROCHI** [comment]
德鲁伊专用头盔最高等级那两个贴图交换错了，狼头显示成鸟头，鸟头显示成狼头；被触发技能最好能筛选掉一大批不被触发的技能，例如被动技能、光环技能、攻击技能

**Comment by daidodo** [comment]
> 关键是在修改中要考究装备外形和名字，还想在套装加成里每多装备一件都有新的绿词缀，所以凡是四件套都是艾尔多套装在UT里改了底材再拿到Edit2里改各种属性，五件套武器只有塔拉夏，防具只有不朽鞋，六件套全在不朽套装里

能否说明一下你的最终需求是什么？

> 德鲁伊专用头盔最高等级那两个贴图交换错了

麻烦提供物品信息和相应图片。另外物品图片是根据物品ID索引的，目前没有展示特殊物品（例如暗金或套装）的专有图片。

> 被触发技能最好能筛选掉一大批不被触发的技能，例如被动技能、光环技能、攻击技能

能否提供更详细的功能描述？例如现有UI或功能，期望的UI或功能？

**Comment by 17OROCHI** [comment]
![20240907231815](https://github.com/user-attachments/assets/25458552-300e-4d55-8305-70566a8c9627)
![20240907234316](https://github.com/user-attachments/assets/d1418277-e346-4205-bf48-33b6c8457817)
贴图搞反了

![20240907234447](https://github.com/user-attachments/assets/14a350ae-941a-407f-88bb-eda1d547929f)
套装直接加绿色组合词缀会在保存存档时出错

![20240907234600](https://github.com/user-attachments/assets/a955d11e-c311-42ee-aaf0-f88bf530dfd0)
被触发的技能列表里，实际上大部分不能触发的，可以过滤掉

**Comment by daidodo** [comment]
> 被触发的技能列表里，实际上大部分不能触发的，可以过滤掉

麻烦单独创建一个issue，方便讨论和解决这个问题：
1. 如果选中了“不能触发”的技能，会发生什么？crash，游戏报错（最好有UI截图），还是没有任何效果？
  * 不同的技能会有不同的结果吗？例如A，B都不可触发，但A没有任何效果，B会导致crash
2. 哪些技能不能触发？对应每个属性代码（195/196/...），应该都有一个列表。有了这些列表，才能过滤它们。

谢谢！

**Comment by daidodo** [comment]
> 贴图搞反了

也请单独开一个issue。谢谢！

**Comment by 17OROCHI** [comment]
大佬，这个帖子放到已经解决里面吧，汉化完善应该也有别的大神会弄的，触发技能我测试完再发帖，底材直接更改我暂时先用Udietoo对付着
