### ISSUE TITLE
德鲁伊专用头盔底材贴图不正确

### ISSUE THREAD

**Issue by 17OROCHI** [daidodo/diablo_edit#67]
Dream Spirit错误使用了Sky Spirit的贴图；而Sky Spirit错误使用了Dream Spirit的贴图；这问题导致了在操作UI里所显示的德鲁伊装备十分别扭

**Comment by 17OROCHI** [comment]
普通和扩展也是同样的问题

**Comment by daidodo** [comment]
Fixed. Please try https://github.com/daidodo/diablo_edit/releases/tag/0.33
