### ISSUE TITLE
Salvation aura not available in item code 151 , pls fix it :)

### ISSUE THREAD

**Issue by zerokos** [daidodo/diablo_edit#7]
Salvation aura not available in item code 151 , pls fix it :)
tool version is 0.4

**Comment by daidodo** [comment]
Thanks for the feedback!

Could you give more details on the issue and share your d2s file?

**Comment by zerokos** [comment]
> Thanks for the feedback!
> 
> Could you give more details on the issue and share your d2s file?
Here is the d2s file , in which salavation aura is not selectable . There should be totally 20 aura ,but you listed only 19 aura，you have  ignored salavation aura anyway. Pls fix it ,thanks
[Sorceress.zip](https://github.com/daidodo/diablo_edit/files/7316619/Sorceress.zip)
![2021-10-10 082959](https://user-images.githubusercontent.com/5483190/136677147-da503012-742e-47eb-8f06-ad9c68f2f01c.jpg)
